### ISSUE TITLE
Currently each Component has to have its own folder

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/gofbp#6]
This is due to the `import` statement in `main.go` - I haven't found a way to import a specific file

There is a probably a better way - this can be low priority

**Comment by emil14** [comment]
https://github.com/jpaulm/gofbp/pull/8/files

> I haven't found a way to import a specific file

There is no way to do it and you don't need to - all files in the package is just a bunch of entities (functions, variables, types).

You only need to import package, you don't need to think about (which file contains an entity that I need?).

**Comment by jpaulm** [comment]
I do need to!  I want eventually to have a bunch of "components", all extending a Component class.  They will all have the same function names...  Go is missing several key features... or I haven't found the answer yet!

**Comment by emil14** [comment]
>  Go is missing several key features

The only key feature that Go is missing is generics (and soon we'll have them). I don't see a case for inheritance, everything could be implemented via composition. Do we have inheritance in FBP? :) 

>  I want eventually to have a bunch of "components", all extending a Component class

This has nothing to with import of specific files. You can have all your components in a single package or in a separate packages depending on what you want. 

---

Could you please describe your `Component` class? Do your components all have same method signatures? If so you can use `interface`. Do you need to reuse methods to avoid repeating their implementation? Struct embedding is the way to go then. 

Please describe your case in more detail and I'll do my best to solve it!

**Comment by jpaulm** [comment]
Both Components are in https://github.com/jpaulm/gofbp/tree/master/components - currently they have to be indifferent folders...  Thx

**Comment by egonelbre** [comment]
Yeah, Go organizes things by package/folder rather than a single file. Which of course sometimes isn't ideal, especially when you have small pieces of code that you might want to import separately. Given the constraint there are two variations of it:

---

First variation, people group several different components into a single package and then import a single package. This means that the functions or types need to be named differently. For example:

```
package components

type Sender struct { ... }
func NewSender() *Sender { return &Sender{ ... } }
func (sender *Sender) Name() string { return "Sender" }
func (sender *Sender) Execute(...) ... { ... }

type Receiver struct { ... }
func NewReceiver() *Receiver { return &Receiver{ ... } }
func (receiver *Receiver) Name() string { return "Receiver" }
func (receiver *Receiver) Execute(...) ... { ... }
```

And when using:

```
import "x/y/z/components"

func main() {
    send := components.NewSender()
    recv := components.NewReceiver()
    ...
```

These components could also be declared in terms of funcs, if they do not hold state.

---

Then the second variations is pretty much what you have:

```
package sender

type Component struct { ... }
func New() *Component { return &Component{ ... } }
func (sender *Component) Name() string { return "Sender" }
func (sender *Component) Execute(...) ... { ... }
```

And using:

```
import (
    "x/y/z/components/sender"
    "x/y/z/components/receiver"
)

func main() {
    send := sender.New()
    recv := receiver.New()
    ...
```

---

Maybe the most common is the third solution where you combine these two approaches. The more complex things have a single component per package and something like string utilities are combined in a single package.

**Comment by jpaulm** [comment]
Hi Egon, I didn't see this - thanks for the feedback!   I may leave the code the way it is for now - apart from adding another folder level - for grouping components.  

The underlying problem, as I see it, is the decision not to include "extends" - plus I would like to be able to pass a "component" to a function...  Both of these are available in Java, C# and C++  , and make component-based development fairly straightforward.  They seem to have, wilfully and without much thought, thrown the baby out with the bathwater!

**Comment by egonelbre** [comment]
> They seem to have, wilfully and without much thought, thrown the baby out with the bathwater!

Usually such questions have a reasoning in the FAQ -- https://golang.org/doc/faq#inheritance. Go is rather opinionated in many cases... one of them being inheritance.

Personally, I've found that almost-always the non-extends ends up being easier to debug and maintain. There have been two exceptions so far over 10 years. But, that of course means restructuring the codebase to prefer composition over inheritance.

In principle the way you would handle it in Go is to define an interface, e.g.:

```
type Component interface {
    In() []*Port
    Out() []*Port
    Name() string
    Run()
}
```

Then implement the interface:

```
type Debugger struct { ... }
func (debug *Debugger) Name() string { return "Debug" }
func (debug *Debugger) Run() string {
    for msg := range debug.inbox {
        fmt.Println(msg)
        debug.outbox <- msg
    }
}
...
```

The question now is, how do you share implementations. There are few common ways:

First approach: duplicate the code. This might not be ideal, but sometimes keeps things really straightforward.

Second approach: define a common type and write wrapping methods:

```
type Messages struct {
    in []*Port
    out []*Port
}

func (m *Messages) In() { return m.in }
func (m *Messages) Out() { return m.out }

type Debugger struct {
    messages *Messages
}
func (debug *Debugger) In() { return debug.messages.In() }
func (debug *Debugger) Out() { return debug.messages.Out() }
```

Obviously, this introduces method duplication. However, as a benefit, it still is very clear in what methods a particular type has.

Third approach would be embedding (https://golang.org/doc/effective_go#embedding):

```
type Debugger struct {
    *Messages
}
```

This ends up forwarding the methods to `*Messages` when there isn't a corresponding one in Debugger. In principle it's the same code as previous, but without the code duplication. Of course, now when calling `.In()` on the `Debugger`, it's not obvious what is being called... however, in this case it's still quite trivial. This can get confusing when you end up embedding a lot of things.

Then there are approaches where you write utility functions to help you handle things. If you have a common behavior for filtering inbound messages, then it can be a regular func rather than a method.

Finally there are code-generation based approaches, where you write some code that generates code for you. This is usually used when all the previous aren't great solution... or it's used as a way to generate a more performant code that's non-trivial to write manual.

**Comment by jpaulm** [comment]
Apparently you can only import packages, but you can reference files, and the unreferenced files are not incuded in the binary...  So that will work!

**Comment by emil14** [comment]
> but you can reference files, and the unreferenced files are not incuded in the binary

Not files but "package members" - functions, types, variables. It does not matter how many files you have, what matters if what package members you have in the package :)
