### ISSUE TITLE
How to pass whole Component to a function

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/gofbp#7]
Can't seem to find a way to pass "Sender" - https://github.com/jpaulm/gofbp/blob/master/components/sender/sender.go - to a function as a whole thing (for now), but I can pass its Execute  function.    This will do for now...

Again, maybe there is a better way!

**Comment by emil14** [comment]
What you mean by "pass Sender as a whole thing"? I don't see such thing as `Sender` :) 

There's of course a `sender.go` file but that's just a file! You have to have some entity (package member) with the name `Sender` to pass it to functions.

Maybe you want to have a type `Sender`? Something like 

```go
type Sender struct{} // could be any type, not only struct

func (s Sender) Execute() { // define "Execute" method on a "Sender" type
  // code goes here
}
```

**Comment by jpaulm** [comment]
The current Sender component - https://github.com/jpaulm/gofbp/blob/master/components/sender/sender.go - has no `struct`, and `Execute` is a function, not a method - does this make a difference?  TIA

Java, C# and C++ all allow one to pass a "class" to a function - I don't see that in Go...?

**Comment by emil14** [comment]
> The current Sender component - https://github.com/jpaulm/gofbp/blob/master/components/sender/sender.go - has no struct, and Execute is a function, not a method - does this make a difference?

Yes it does. Because you want to "pass Sender" to function, but the only "sender" I can see is `sender.go` file. But in go file itself is not an object (like in Java every file is a class), it's just a "place" for package members. Go compiler does not care about specific files and you don't need too.

> Java, C# and C++ all allow one to pass a "class" to a function - I don't see that in Go...?

So what you need is to create a `type`, give it a name (probably `Sender`) and define `Execute` method on that type. After that you can import this package from outside, create a value of your `Sender` type and pass it to function.

**Comment by jpaulm** [comment]
We are importing the whole package, but Golang only includes referenced components in the compiled output.  See  the components in https://github.com/jpaulm/gofbp/tree/master/components/testrtn .  Works pretty well!
